version: 1
builder:
  configs:
  - platform: ios
    scheme: CocoaAliases
    documentation_targets:
      - CocoaAliases

  - platform: macos-spm
    scheme: CocoaAliases
    documentation_targets:
      - CocoaAliases

  - platform: tvos
    scheme: CocoaAliases
    documentation_targets:
      - CocoaAliases

  - platform: watchos
    scheme: CocoaAliases
    documentation_targets:
      - CocoaAliases

  - platform: visionOS
    scheme: CocoaAliases
    documentation_targets:
      - CocoaAliases

  - platform: macos-xcodebuild
    scheme: CocoaAliases
