version: 1
builder:
  configs:
  - platform: ios
    documentation_targets:
      - CocoaAliases

  - platform: macos-spm
    documentation_targets:
      - CocoaAliases

  - platform: tvos
    documentation_targets:
      - CocoaAliases

  - platform: watchos
    documentation_targets:
      - CocoaAliases

  - platform: visionOS
    documentation_targets:
      - CocoaAliases

  - platform: macos-xcodebuild
  - platform: android

  - platform: linux
    swift_version: '5.9'

  - platform: linux
    swift_version: '6.0'
